[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "18.20.0"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


